from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 353)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 353))
        MainWindow.setMaximumSize(QtCore.QSize(300, 353))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(22)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(0, 30, 225, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(22)
        self.l1.setFont(font)
        self.l1.setStyleSheet("background-color: rgb(180, 180, 180);border-color: rgb(0, 0, 0);")
        self.l1.setText("")
        self.l1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(0, 0, 225, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(15)
        self.l2.setFont(font)
        self.l2.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.l2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.l2.setText("")
        self.l2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.l2.setObjectName("l2")
        self.bcl = QtWidgets.QPushButton(self.centralwidget)
        self.bcl.setGeometry(QtCore.QRect(225, 0, 75, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.bcl.setFont(font)
        self.bcl.setStyleSheet("background-color: rgb(255, 61, 64);color: rgb(0, 255, 127);")
        self.bcl.setObjectName("bcl")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 90, 341, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.b3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b3.sizePolicy().hasHeightForWidth())
        self.b3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setStyleSheet("color :  rgb(255, 255, 255);background-color : rgb(58, 58, 58)")
        self.b3.setObjectName("b3")
        self.gridLayout.addWidget(self.b3, 2, 3, 1, 1)
        self.bmul = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bmul.sizePolicy().hasHeightForWidth())
        self.bmul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.bmul.setFont(font)
        self.bmul.setAutoFillBackground(False)
        self.bmul.setStyleSheet("background-color: rgb(255, 170, 0);color: rgb(9, 58, 132);")
        self.bmul.setObjectName("bmul")
        self.gridLayout.addWidget(self.bmul, 2, 4, 1, 1)
        self.b7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b7.sizePolicy().hasHeightForWidth())
        self.b7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setStyleSheet("color :  rgb(255, 255, 255);background-color : rgb(58, 58, 58);selection-background-color: rgb(0, 170, 255);selection-color: rgb(0, 120, 215);")
        self.b7.setObjectName("b7")
        self.gridLayout.addWidget(self.b7, 0, 0, 1, 1)
        self.b4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b4.sizePolicy().hasHeightForWidth())
        self.b4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setStyleSheet("color :  rgb(255, 255, 255);background-color : rgb(58, 58, 58)")
        self.b4.setObjectName("b4")
        self.gridLayout.addWidget(self.b4, 1, 0, 1, 1)
        self.b9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b9.sizePolicy().hasHeightForWidth())
        self.b9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setStyleSheet("color :  rgb(255, 255, 255);background-color : rgb(58, 58, 58)")
        self.b9.setObjectName("b9")
        self.gridLayout.addWidget(self.b9, 0, 3, 1, 1)
        self.b2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b2.sizePolicy().hasHeightForWidth())
        self.b2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setStyleSheet("color :  rgb(255, 255, 255);background-color : rgb(58, 58, 58)")
        self.b2.setObjectName("b2")
        self.gridLayout.addWidget(self.b2, 2, 1, 1, 1)
        self.beq = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beq.sizePolicy().hasHeightForWidth())
        self.beq.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 58, 132, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.beq.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.beq.setFont(font)
        self.beq.setStyleSheet("background-color: rgb(255, 170, 0);color: rgb(9, 58, 132);")
        self.beq.setObjectName("beq")
        self.gridLayout.addWidget(self.beq, 3, 3, 1, 1)
        self.bminus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bminus.sizePolicy().hasHeightForWidth())
        self.bminus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.bminus.setFont(font)
        self.bminus.setStyleSheet("background-color: rgb(255, 170, 0);color: rgb(9, 58, 132);")
        self.bminus.setObjectName("bminus")
        self.gridLayout.addWidget(self.bminus, 1, 4, 1, 1)
        self.b8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b8.sizePolicy().hasHeightForWidth())
        self.b8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setStyleSheet("color :  rgb(255, 255, 255);background-color : rgb(58, 58, 58)")
        self.b8.setObjectName("b8")
        self.gridLayout.addWidget(self.b8, 0, 1, 1, 1)
        self.bdiv = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bdiv.sizePolicy().hasHeightForWidth())
        self.bdiv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.bdiv.setFont(font)
        self.bdiv.setStyleSheet("background-color: rgb(255, 170, 0);color: rgb(9, 58, 132);")
        self.bdiv.setIconSize(QtCore.QSize(16, 16))
        self.bdiv.setAutoDefault(False)
        self.bdiv.setDefault(False)
        self.bdiv.setFlat(False)
        self.bdiv.setObjectName("bdiv")
        self.gridLayout.addWidget(self.bdiv, 3, 4, 1, 1)
        self.b6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b6.sizePolicy().hasHeightForWidth())
        self.b6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setStyleSheet("color :  rgb(255, 255, 255);background-color : rgb(58, 58, 58)")
        self.b6.setObjectName("b6")
        self.gridLayout.addWidget(self.b6, 1, 3, 1, 1)
        self.b1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1.sizePolicy().hasHeightForWidth())
        self.b1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setStyleSheet("color :  rgb(255, 255, 255);background-color : rgb(58, 58, 58)")
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 2, 0, 1, 1)
        self.b0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b0.sizePolicy().hasHeightForWidth())
        self.b0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.b0.setFont(font)
        self.b0.setStyleSheet("color :  rgb(255, 255, 255);background-color : rgb(58, 58, 58)")
        self.b0.setObjectName("b0")
        self.gridLayout.addWidget(self.b0, 3, 1, 1, 1)
        self.b5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b5.sizePolicy().hasHeightForWidth())
        self.b5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setStyleSheet("color :  rgb(255, 255, 255);background-color : rgb(58, 58, 58)")
        self.b5.setObjectName("b5")
        self.gridLayout.addWidget(self.b5, 1, 1, 1, 1)
        self.bplus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bplus.sizePolicy().hasHeightForWidth())
        self.bplus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.bplus.setFont(font)
        self.bplus.setStyleSheet("background-color: rgb(255, 170, 0);color: rgb(9, 58, 132);")
        self.bplus.setObjectName("bplus")
        self.gridLayout.addWidget(self.bplus, 0, 4, 1, 1)
        self.bdot = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bdot.sizePolicy().hasHeightForWidth())
        self.bdot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.bdot.setFont(font)
        self.bdot.setStyleSheet("color :  rgb(255, 255, 255);background-color : rgb(58, 58, 58)")
        self.bdot.setObjectName("bdot")
        self.gridLayout.addWidget(self.bdot, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.bcl.setText(_translate("MainWindow", "Cl"))
        self.b3.setText(_translate("MainWindow", "3"))
        self.bmul.setText(_translate("MainWindow", "*"))
        self.b7.setText(_translate("MainWindow", "7"))
        self.b4.setText(_translate("MainWindow", "4"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.b2.setText(_translate("MainWindow", "2"))
        self.beq.setText(_translate("MainWindow", "="))
        self.bminus.setText(_translate("MainWindow", "-"))
        self.b8.setText(_translate("MainWindow", "8"))
        self.bdiv.setText(_translate("MainWindow", "/"))
        self.b6.setText(_translate("MainWindow", "6"))
        self.b1.setText(_translate("MainWindow", "1"))
        self.b0.setText(_translate("MainWindow", "0"))
        self.b5.setText(_translate("MainWindow", "5"))
        self.bplus.setText(_translate("MainWindow", "+"))
        self.bdot.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
